"""CanvasExporter — 연구 결과를 캔버스 HTML로 export

Phase 6 (OpenClaw Canvas / PDF 스킬 강화)

세 렌더러를 조합하여 단일 self-contained HTML을 생성한다.
- StructuredMarkdownRenderer: 구조화된 마크다운 → HTML 변환
- ChartRenderer: 소스 분포 차트 (base64 PNG 인라인)
- MermaidDiagramRenderer: 인용 관계 마인드맵 (Mermaid CDN 렌더링)
"""

import asyncio
import logging
import re
from typing import Optional

from .base import BaseExporter, ResearchReport, safe_url

logger = logging.getLogger(__name__)

CANVAS_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.esm.min.mjs';
    mermaid.initialize({{ startOnLoad: true, theme: 'default' }});
  </script>
  <noscript><style>.mermaid {{ white-space: pre; font-family: monospace; }}</style></noscript>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.7;
      max-width: 960px;
      margin: 0 auto;
      padding: 24px;
      background: #f9fafb;
      color: #1a202c;
    }}
    .canvas-container {{
      background: #fff;
      border-radius: 10px;
      box-shadow: 0 2px 8px rgba(0,0,0,.08);
      padding: 48px;
    }}
    h1 {{ color: #2d3748; border-bottom: 3px solid #4299e1; padding-bottom: 8px; }}
    h2 {{ color: #4a5568; margin-top: 32px; }}
    h3 {{ color: #718096; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
    th {{ background: #edf2f7; font-weight: 600; }}
    tr:nth-child(even) {{ background: #f7fafc; }}
    code {{ background: #edf2f7; padding: 2px 6px; border-radius: 4px; font-size: .9em; }}
    pre {{ background: #2d3748; color: #e2e8f0; padding: 16px; border-radius: 6px; overflow-x: auto; }}
    blockquote {{ border-left: 4px solid #4299e1; margin: 0; padding-left: 16px; color: #718096; }}
    a {{ color: #4299e1; }}
    .section-charts {{ margin: 32px 0; }}
    .chart-item {{ margin: 24px 0; text-align: center; }}
    .chart-item img {{ max-width: 100%; border-radius: 6px; box-shadow: 0 1px 4px rgba(0,0,0,.1); }}
    .chart-item p {{ font-size: .9em; color: #718096; margin-top: 8px; }}
    .section-diagram {{ margin: 32px 0; }}
    .mermaid {{ background: #f7fafc; border-radius: 6px; padding: 16px; }}
    .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0;
               text-align: center; font-size: .85em; color: #a0aec0; }}
  </style>
</head>
<body>
  <div class="canvas-container">
    {markdown_html}
    {charts_html}
    {diagram_html}
    <div class="footer">
      <p>Session ID: <code>{session_id}</code> &nbsp;|&nbsp; Generated by NEOS Research Engine</p>
    </div>
  </div>
</body>
</html>
"""


class CanvasExporter(BaseExporter):
    """연구 리포트를 캔버스 HTML로 export.

    마크다운 구조 + 차트 이미지 + Mermaid 다이어그램을
    단일 self-contained HTML 파일로 묶는다.
    """

    async def export(
        self,
        report: ResearchReport,
        output_path: Optional[str] = None,
        **options,
    ) -> bytes:
        from neos.skills.builtin.canvas.renderers import (
            StructuredMarkdownRenderer,
            ChartRenderer,
            MermaidDiagramRenderer,
        )

        md_text = StructuredMarkdownRenderer().render(report)
        charts = await asyncio.to_thread(ChartRenderer().render, report)
        mermaid_text = MermaidDiagramRenderer().render(report)

        markdown_html = _markdown_to_html(md_text)
        charts_html = _build_charts_html(charts)
        diagram_html = _build_diagram_html(mermaid_text)

        html = CANVAS_HTML_TEMPLATE.format(
            title=_escape(report.query),
            markdown_html=markdown_html,
            charts_html=charts_html,
            diagram_html=diagram_html,
            session_id=report.session_id,
        )
        content = html.encode("utf-8")

        if output_path:
            with open(output_path, "wb") as f:
                f.write(content)

        return content

    def get_mime_type(self) -> str:
        return "text/html"

    def get_file_extension(self) -> str:
        return "html"


# ──────────────────────────────────────────────
# 내부 헬퍼
# ──────────────────────────────────────────────

def _markdown_to_html(md: str) -> str:
    """간단한 Markdown → HTML 변환 (외부 의존성 없음).

    지원 구문: h1-h3, **bold**, *italic*, `code`, [link](url),
              | table |, > blockquote, --- hr, 빈 줄 단락.
    """
    lines = md.split("\n")
    html_lines = []
    in_table = False
    in_code_block = False

    for line in lines:
        # 코드 블록
        if line.startswith("```"):
            if in_code_block:
                html_lines.append("</code></pre>")
                in_code_block = False
            else:
                html_lines.append("<pre><code>")
                in_code_block = True
            continue

        if in_code_block:
            html_lines.append(_escape(line))
            continue

        # 테이블
        if line.startswith("|") and line.endswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if not in_table:
                in_table = True
                html_lines.append("<table>")
                html_lines.append(
                    "<tr>" + "".join(f"<th>{_escape(c)}</th>" for c in cells) + "</tr>"
                )
            elif re.match(r"^\s*[-|: ]+$", line):
                pass  # separator row
            else:
                html_lines.append(
                    "<tr>" + "".join(f"<td>{_escape(c)}</td>" for c in cells) + "</tr>"
                )
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False

        # 헤딩
        m = re.match(r"^(#{1,3})\s+(.+)$", line)
        if m:
            level = len(m.group(1))
            html_lines.append(f"<h{level}>{_inline(m.group(2))}</h{level}>")
            continue

        # 수평선
        if re.match(r"^-{3,}$", line.strip()):
            html_lines.append("<hr>")
            continue

        # 인용
        if line.startswith("> "):
            html_lines.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
            continue

        # 목록
        if re.match(r"^\d+\.\s", line):
            html_lines.append(f"<p>{_inline(line)}</p>")
            continue

        # 빈 줄
        if not line.strip():
            html_lines.append("")
            continue

        html_lines.append(f"<p>{_inline(line)}</p>")

    if in_table:
        html_lines.append("</table>")
    if in_code_block:
        html_lines.append("</code></pre>")

    return "\n".join(html_lines)


def _safe_url(url: str) -> str:
    """http/https 스킴만 허용. 그 외는 '#'으로 대체 (CR-P6-02: javascript: URI 차단).

    구현은 `base.safe_url` 로 옮겼다 -- 이 수정이 canvas 에만 도착해 있었고
    html_exporter 는 뚫린 채였다(2026-09-05). 이름을 남기는 것은 이 모듈 안의
    호출부(`_inline`) 때문이고, 로직 사본은 하나다.
    """
    return safe_url(url)


def _inline(text: str) -> str:
    """인라인 마크다운(bold, italic, code, link) 처리."""
    # **bold**
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # *italic*
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # `code`
    text = re.sub(r"`(.+?)`", lambda m: f"<code>{_escape(m.group(1))}</code>", text)
    # [text](url) — URL 스킴 검증 적용
    text = re.sub(
        r"\[(.+?)\]\((.+?)\)",
        lambda m: f'<a href="{_safe_url(m.group(2))}" target="_blank">{m.group(1)}</a>',
        text,
    )
    return text


def _build_charts_html(charts: list) -> str:
    if not charts:
        return ""
    items = []
    for c in charts:
        title = _escape(c.get("title", ""))
        alt = _escape(c.get("alt", title))
        b64 = c.get("image_b64", "")
        items.append(
            f'<div class="chart-item">'
            f'<img src="data:image/png;base64,{b64}" alt="{alt}">'
            f"<p>{title}</p></div>"
        )
    return f'<div class="section-charts"><h2>차트</h2>{"".join(items)}</div>'


def _build_diagram_html(mermaid_text: str) -> str:
    if not mermaid_text.strip():
        return ""
    # Mermaid는 HTML 엔티티를 그대로 파싱하므로 _escape() 사용 가능 (CR-P6-01: XSS 수정)
    safe = _escape(mermaid_text)
    return (
        f'<div class="section-diagram"><h2>소스 관계도</h2>'
        f'<div class="mermaid">{safe}</div></div>'
    )


def _escape(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
