"""HTML Exporter"""

import logging
from typing import Optional

from .base import BaseExporter, ResearchReport, safe_url

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
            color: #333;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        .metadata {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        .citation {{
            padding: 10px;
            background: #f8f9fa;
            border-left: 3px solid #3498db;
            margin: 10px 0;
        }}
        .search-result {{
            padding: 15px;
            background: #fafafa;
            border-radius: 5px;
            margin: 15px 0;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .quality-badge {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }}
        .quality-high {{ background: #d4edda; color: #155724; }}
        .quality-medium {{ background: #fff3cd; color: #856404; }}
        .quality-low {{ background: #f8d7da; color: #721c24; }}
    </style>
</head>
<body>
    <div class="container">
        {content}
        <div class="footer">
            <p>Report ID: {session_id}</p>
            <p>Generated by NEOS Research Engine</p>
        </div>
    </div>
</body>
</html>"""


class HTMLExporter(BaseExporter):
    """연구 리포트를 HTML로 export"""

    async def export(
        self,
        report: ResearchReport,
        output_path: Optional[str] = None,
        **options,
    ) -> bytes:
        # Build content sections
        sections = []

        # Header
        sections.append(f"<h1>{_escape(report.query)}</h1>")
        sections.append(
            f"<p><em>Generated: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}</em></p>"
        )

        # Quality badge
        if report.quality_score is not None:
            css_class = (
                "quality-high" if report.quality_score >= 0.8
                else "quality-medium" if report.quality_score >= 0.5
                else "quality-low"
            )
            sections.append(
                f'<p>Quality: <span class="quality-badge {css_class}">'
                f"{report.quality_score:.2f}</span></p>"
            )

        # Metadata
        if report.metadata:
            items = "".join(
                f"<div><strong>{k.replace('_', ' ').title()}:</strong> {_escape(str(v))}</div>"
                for k, v in report.metadata.items()
            )
            sections.append(f'<div class="metadata"><h2>Metadata</h2>{items}</div>')

        # Main response
        sections.append("<h2>Research Findings</h2>")
        sections.append(f"<div>{_escape(report.response)}</div>")

        # Citations
        if report.citations:
            sections.append("<h2>Sources</h2>")
            for i, c in enumerate(report.citations, 1):
                title = _escape(c.get("title", "Untitled"))
                # 제목만 이스케이프하고 URL 은 날것으로 넣고 있었다 -- citations
                # 의 url 은 검색 결과에서 오는 외부 데이터다(`safe_url` 독스트링).
                url = safe_url(c.get("url") or "")
                sections.append(
                    f'<div class="citation"><strong>{i}.</strong> '
                    f'<a href="{url}" target="_blank">{title}</a></div>'
                )

        # Search results
        if report.search_results:
            sections.append("<h2>Detailed Search Results</h2>")
            for i, r in enumerate(report.search_results[:10], 1):
                title = _escape(r.get("title", "Untitled"))
                # citations 와 **같은 외부 데이터**이고 같은 구멍이었다. 이쪽은
                # URL 을 본문 텍스트로도 내보내므로 두 자리 다 거쳐야 한다.
                url = safe_url(r.get("url") or "")
                content = _escape((r.get("content") or "")[:300])
                sections.append(
                    f'<div class="search-result">'
                    f"<h3>{i}. {title}</h3>"
                    f'<p><strong>Source:</strong> <a href="{url}" target="_blank">{url}</a></p>'
                    f"<p>{content}</p></div>"
                )

        content = "\n".join(sections)
        html = HTML_TEMPLATE.format(
            title=_escape(report.query),
            content=content,
            session_id=report.session_id,
        )
        html_bytes = html.encode("utf-8")

        if output_path:
            with open(output_path, "wb") as f:
                f.write(html_bytes)

        return html_bytes

    def get_mime_type(self) -> str:
        return "text/html"

    def get_file_extension(self) -> str:
        return "html"


def _escape(text: str) -> str:
    """Basic HTML escaping"""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
