"""Markdown Exporter"""

import logging
from typing import Optional

from .base import BaseExporter, ResearchReport

logger = logging.getLogger(__name__)


class MarkdownExporter(BaseExporter):
    """연구 리포트를 Markdown으로 export"""

    async def export(
        self,
        report: ResearchReport,
        output_path: Optional[str] = None,
        include_metadata: bool = True,
        **options,
    ) -> bytes:
        md = []

        # 헤더
        md.append(f"# Research Report: {report.query}\n")
        md.append(f"*Generated: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}*\n")
        md.append("---\n")

        # 메타데이터
        if include_metadata and report.metadata:
            md.append("## Metadata\n")
            for key, value in report.metadata.items():
                md.append(f"- **{key.replace('_', ' ').title()}**: {value}\n")
            md.append("\n")

        # 품질 점수
        if report.quality_score is not None:
            md.append(f"**Quality Score**: {report.quality_score:.2f}\n\n")

        # 연구 결과
        md.append("## Research Findings\n")
        md.append(f"{report.response}\n\n")

        # 출처/인용
        if report.citations:
            md.append("## Sources\n")
            for i, citation in enumerate(report.citations, 1):
                title = citation.get("title", "Untitled")
                url = citation.get("url", "#")
                md.append(f"{i}. [{title}]({url})\n")
            md.append("\n")

        # 검색 결과 요약
        if report.search_results:
            md.append("## Detailed Search Results\n")
            for i, result in enumerate(report.search_results[:10], 1):
                md.append(f"### {i}. {result.get('title', 'Untitled')}\n")
                md.append(f"**Source**: {result.get('url', 'N/A')}\n\n")
                content = result.get("content", "")
                if content:
                    snippet = content[:300] + "..." if len(content) > 300 else content
                    md.append(f"{snippet}\n\n")

        # Fact check
        if report.fact_check_result:
            contradictions = report.fact_check_result.get("contradictions", [])
            if contradictions:
                md.append("## Fact Check Results\n")
                md.append("### Contradictions Found\n")
                for c in contradictions:
                    md.append(f"- {c.get('description', '')}\n")
                md.append("\n")

        # 푸터
        md.append("---\n")
        md.append(f"*Report ID: {report.session_id}*\n")
        md.append("*Generated by NEOS Research Engine*\n")

        content = "".join(md).encode("utf-8")

        if output_path:
            with open(output_path, "wb") as f:
                f.write(content)

        return content

    def get_mime_type(self) -> str:
        return "text/markdown"

    def get_file_extension(self) -> str:
        return "md"
