host_centrality_store_path = "./data/centrality"
limit_warc_files = 20
output_path = "./data/index"
# minimum_clean_words = 40

[warc_source]
folder = "./data"
names = ["sample.warc.gz"]
type = "Local"
