@startuml openhands
!pragma useIntermediatePackages false

class neos.action.agent.AgentEchoAction {
  content: str
  runnable: bool
  action: str
}
class neos.action.agent.AgentFinishAction {
  runnable: bool
  action: str
}
class neos.observation.AgentMessageObservation {
  role: str
  observation: str
}
class neos.action.agent.AgentSummarizeAction {
  summary: str
  action: str
}
class neos.action.agent.AgentThinkAction {
  thought: str
  runnable: bool
  action: str
}
class neos.action.base.ExecutableAction {
}
class neos.action.base.NotExecutableAction {
}
class neos.observation.Observation {
  content: str
}
class neos.action.base.Action {
}
class neos.action.base.NullAction {
  action: str
}
class neos.action.bash.CmdRunAction {
  command: str
  action: str
}
class neos.action.browse.BrowseURLAction {
  url: str
  action: str
}
class neos.observation.BrowserOutputObservation {
  url: str
  status_code: int
  error: bool
  observation: str
}
class neos.action.fileop.FileReadAction {
  path: str
  action: str
}
class neos.observation.FileReadObservation {
  path: str
  observation: str
}
class neos.action.fileop.FileWriteAction {
  path: str
  contents: str
  action: str
}
class neos.observation.FileWriteObservation {
  path: str
  observation: str
}
class neos.action.tasks.AddTaskAction {
  parent: str
  goal: str
  subtasks: list
  action: str
}
class neos.action.tasks.ModifyTaskAction {
  id: str
  state: str
  action: str
}
abstract class neos.agent.Agent {
  _registry: Dict[str, Type[Agent]] {static}
  llm: LLM
  _complete: None
}
class neos.llm.llm.LLM {
  model: None
  api_key: None
  base_url: None
  _debug_dir: None
  _debug_idx: None
  _debug_id: None
  _completion: None
}
class neos.controller.agent_controller.AgentController {
  agent: Agent
  max_iterations: int
  workdir: str
  command_manager: CommandManager
  state: State
  plan: Plan
  callbacks: List[Callable]
}
class neos.observation.AgentErrorObservation {
  observation: str
}
class neos.controller.command_manager.CommandManager {
  directory: None
  shell: None
}
class neos.observation.NullObservation {
  observation: str
}
class neos.plan.Plan {
  main_goal: str {static}
  task: Task {static}
  main_goal: str
  task: None
}
class neos.state.State {
  plan: Plan
  iteration: int
  history: List[Tuple[Action, Observation]]
  updated_info: List[Tuple[Action, Observation]]
}
class neos.observation.CmdOutputObservation {
  command: str
  exit_code: int
  observation: str
}
class neos.sandbox.sandbox.DockerInteractive {
  instance_id: None
  instance_id: None
  workspace_dir: None
  workspace_dir: None
  workspace_dir: None
  timeout: int
  base_container_image: None
  container_name: None
}
class neos.observation.UserMessageObservation {
  role: str
  observation: str
}
class neos.plan.Task {
  id: str {static}
  goal: str {static}
  parent: Task | None {static}
  subtasks: List[Task] {static}
  id: None
  id: None
  parent: None
  goal: str
  subtasks: None
}

class neos.server.session.Session {
  websocket: None
  controller: Optional[AgentController]
  agent: Optional[Agent]
  agent_task: None
}

neos.action.base.ExecutableAction <|-- neos.action.agent.AgentEchoAction
neos.action.base.NotExecutableAction <|-- neos.action.agent.AgentFinishAction
neos.observation.Observation <|-- neos.observation.AgentMessageObservation
neos.action.base.NotExecutableAction <|-- neos.action.agent.AgentSummarizeAction
neos.action.base.NotExecutableAction <|-- neos.action.agent.AgentThinkAction
neos.action.base.Action <|-- neos.action.base.ExecutableAction
neos.action.base.Action <|-- neos.action.base.NotExecutableAction
neos.action.base.NotExecutableAction <|-- neos.action.base.NullAction
neos.action.base.ExecutableAction <|-- neos.action.bash.CmdRunAction
neos.action.base.ExecutableAction <|-- neos.action.browse.BrowseURLAction
neos.observation.Observation <|-- neos.observation.BrowserOutputObservation
neos.action.base.ExecutableAction <|-- neos.action.fileop.FileReadAction
neos.observation.Observation <|-- neos.observation.FileReadObservation
neos.action.base.ExecutableAction <|-- neos.action.fileop.FileWriteAction
neos.observation.Observation <|-- neos.observation.FileWriteObservation
neos.action.base.NotExecutableAction <|-- neos.action.tasks.AddTaskAction
neos.action.base.NotExecutableAction <|-- neos.action.tasks.ModifyTaskAction
neos.agent.Agent *-- neos.agent.Agent
neos.agent.Agent *-- neos.llm.llm.LLM
neos.controller.agent_controller.AgentController *-- neos.agent.Agent
neos.observation.Observation <|-- neos.observation.AgentErrorObservation
neos.observation.Observation <|-- neos.observation.NullObservation
neos.plan.Plan *-- neos.plan.Task
neos.state.State *-- neos.plan.Plan
neos.state.State *-- neos.observation.CmdOutputObservation
neos.state.State *-- neos.action.base.Action
neos.state.State *-- neos.observation.Observation
neos.observation.Observation <|-- neos.observation.CmdOutputObservation
neos.observation.Observation <|-- neos.observation.UserMessageObservation
neos.plan.Task *-- neos.plan.Task
neos.server.session.Session *-- neos.controller.agent_controller.AgentController
neos.server.session.Session *-- neos.agent.Agent
neos.controller.agent_controller.AgentController -> neos.state.State
neos.controller.agent_controller.AgentController -> neos.plan.Plan
neos.controller.agent_controller.AgentController -> neos.controller.command_manager.CommandManager
neos.controller.command_manager.CommandManager -> neos.sandbox.sandbox.DockerInteractive

footer Based on f3fda42; Generated by //py2puml//
@enduml
