"""Write committed web/lib/ai/catalog.generated.ts from to_picker_payload().

Do not hand-edit the generated file. After changing models.yaml:

    python scripts/generate_catalog_fallback.py

CI runs this script and `git diff --exit-code -- web/lib/ai/catalog.generated.ts`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from neos.config.model_config import model_config  # noqa: E402
from neos.config.model_identity import to_picker_payload  # noqa: E402
from neos.config.schema import ModelRoutingConfig  # noqa: E402
OUT_PATH = ROOT / "web" / "lib" / "ai" / "catalog.generated.ts"


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _ts_record(mapping: dict[str, str]) -> str:
    if not mapping:
        return "{}"
    lines = [f"  {_ts_string(key)}: {_ts_string(value)}," for key, value in mapping.items()]
    return "{\n" + "\n".join(lines) + "\n}"


def render() -> str:
    catalog = model_config.catalog
    payload = to_picker_payload(catalog, ModelRoutingConfig())
    default_pin = next(
        (row.catalog_id for row in payload.models if row.id == payload.default_id),
        "",
    )

    # raw → pin for mapToBackendModelName step 3. Live picker ids first so a
    # later remap of the same raw string (should not happen) cannot hide them.
    fallback_map: dict[str, str] = {}
    for row in payload.models:
        fallback_map[row.id] = row.catalog_id
    for raw, pin in catalog.remaps.items():
        fallback_map[raw] = pin

    model_blocks: list[str] = []
    for row in payload.models:
        role_alias = "null" if row.role_alias is None else _ts_string(row.role_alias)
        model_blocks.append(
            "  {\n"
            f"    id: {_ts_string(row.id)},\n"
            f"    catalog_id: {_ts_string(row.catalog_id)},\n"
            f"    name: {_ts_string(row.name)},\n"
            f"    provider: {_ts_string(row.provider)},\n"
            f"    description: {_ts_string(row.description)},\n"
            f"    thinking: {_ts_string(row.thinking)},\n"
            f"    vision: {str(row.vision).lower()},\n"
            f"    role_alias: {role_alias},\n"
            f"    default: {str(row.default).lower()},\n"
            "  },"
        )

    return (
        "/* AUTO-GENERATED by scripts/generate_catalog_fallback.py. Do not hand-edit. */\n"
        "\n"
        "export type GeneratedPickerRow = {\n"
        "  id: string;\n"
        "  catalog_id: string;\n"
        "  name: string;\n"
        "  provider: string;\n"
        "  description: string;\n"
        '  thinking: "adaptive" | "budgeted" | "none";\n'
        "  vision: boolean;\n"
        "  role_alias: string | null;\n"
        "  default: boolean;\n"
        "};\n"
        "\n"
        f"export const generatedDefaultId = {_ts_string(payload.default_id)};\n"
        f"export const generatedDefaultPin = {_ts_string(default_pin)};\n"
        "\n"
        "export const generatedModels: GeneratedPickerRow[] = [\n"
        + "\n".join(model_blocks)
        + "\n];\n"
        "\n"
        "/** raw cookie / gateway id → catalog pin (mapToBackendModelName step 3) */\n"
        f"export const generatedFallbackMap: Record<string, string> = {_ts_record(fallback_map)};\n"
        "\n"
        "/** raw cookie / gateway id → gateway_id still in models[] */\n"
        f"export const generatedRemaps: Record<string, string> = {_ts_record(payload.remaps)};\n"
        "\n"
        "/** helper slot → catalog pin (title / artifact / fast) */\n"
        f"export const generatedAux: Record<string, string> = {_ts_record(catalog.aux)};\n"
        "\n"
        "export const generatedCatalog = {\n"
        "  version: 1,\n"
        "  default_id: generatedDefaultId,\n"
        "  default_pin: generatedDefaultPin,\n"
        "  models: generatedModels,\n"
        "  remaps: generatedRemaps,\n"
        "  aux: generatedAux,\n"
        "};\n"
    )


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
