/* AUTO-GENERATED by scripts/generate_catalog_fallback.py. Do not hand-edit. */

export type GeneratedPickerRow = {
  id: string;
  catalog_id: string;
  name: string;
  provider: string;
  description: string;
  thinking: "adaptive" | "budgeted" | "none";
  vision: boolean;
  role_alias: string | null;
  default: boolean;
};

export const generatedDefaultId = "anthropic/claude-sonnet-5";
export const generatedDefaultPin = "claude-sonnet-5";

export const generatedModels: GeneratedPickerRow[] = [
  {
    id: "anthropic/claude-sonnet-5",
    catalog_id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "anthropic",
    description: "Best balance of speed, intelligence, and cost",
    thinking: "adaptive",
    vision: true,
    role_alias: "sonnet-5",
    default: true,
  },
  {
    id: "anthropic/claude-opus-5.5",
    catalog_id: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    provider: "anthropic",
    description: "Most capable Anthropic model",
    thinking: "adaptive",
    vision: true,
    role_alias: "opus-5.5",
    default: false,
  },
  {
    id: "anthropic/claude-haiku-4.5",
    catalog_id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    description: "Fast and affordable, great for everyday tasks",
    thinking: "budgeted",
    vision: true,
    role_alias: "haiku-4.5",
    default: false,
  },
  {
    id: "anthropic/claude-sonnet-4.5",
    catalog_id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5",
    provider: "anthropic",
    description: "Previous-generation balanced model",
    thinking: "budgeted",
    vision: true,
    role_alias: null,
    default: false,
  },
  {
    id: "anthropic/claude-sonnet-4.5-thinking",
    catalog_id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5 (Thinking)",
    provider: "reasoning",
    description: "Extended thinking for complex problems",
    thinking: "budgeted",
    vision: true,
    role_alias: null,
    default: false,
  },
  {
    id: "openai/gpt-6-sol",
    catalog_id: "gpt-6-sol",
    name: "GPT-6 Sol",
    provider: "openai",
    description: "Most capable OpenAI model",
    thinking: "none",
    vision: true,
    role_alias: null,
    default: false,
  },
  {
    id: "openai/gpt-6-luna",
    catalog_id: "gpt-6-luna",
    name: "GPT-6 Luna",
    provider: "openai",
    description: "Fast and affordable OpenAI model",
    thinking: "none",
    vision: true,
    role_alias: null,
    default: false,
  },
];

/** raw cookie / gateway id → catalog pin (mapToBackendModelName step 3) */
export const generatedFallbackMap: Record<string, string> = {
  "anthropic/claude-sonnet-5": "claude-sonnet-5",
  "anthropic/claude-opus-5.5": "claude-opus-5-5",
  "anthropic/claude-haiku-4.5": "claude-haiku-4-5-20251001",
  "anthropic/claude-sonnet-4.5": "claude-sonnet-4-5-20250929",
  "anthropic/claude-sonnet-4.5-thinking": "claude-sonnet-4-5-20250929",
  "openai/gpt-6-sol": "gpt-6-sol",
  "openai/gpt-6-luna": "gpt-6-luna",
  "anthropic/claude-opus-5": "claude-opus-5-5",
  "openai/gpt-5.6-sol": "gpt-6-sol",
  "openai/gpt-5.6-terra": "gpt-6-sol",
  "openai/gpt-4o": "gpt-6-sol",
  "openai/gpt-4o-mini": "gpt-6-sol",
  "openai/gpt-4.1": "gpt-6-sol",
  "openai/gpt-4.1-mini": "gpt-6-sol",
  "anthropic/claude-3.7-sonnet-thinking": "claude-sonnet-4-5-20250929",
  "anthropic/claude-opus-4.5": "claude-opus-5-5",
  "google/gemini-2.5-flash-lite": "claude-sonnet-5",
  "google/gemini-3-pro-preview": "claude-sonnet-5",
  "xai/grok-4.1-fast-non-reasoning": "claude-sonnet-5",
  "xai/grok-code-fast-1-thinking": "claude-sonnet-5",
};

/** raw cookie / gateway id → gateway_id still in models[] */
export const generatedRemaps: Record<string, string> = {
  "anthropic/claude-opus-5": "anthropic/claude-opus-5.5",
  "openai/gpt-5.6-sol": "openai/gpt-6-sol",
  "openai/gpt-5.6-terra": "openai/gpt-6-sol",
  "openai/gpt-4o": "openai/gpt-6-sol",
  "openai/gpt-4o-mini": "openai/gpt-6-sol",
  "openai/gpt-4.1": "openai/gpt-6-sol",
  "openai/gpt-4.1-mini": "openai/gpt-6-sol",
  "anthropic/claude-3.7-sonnet-thinking": "anthropic/claude-sonnet-4.5",
  "anthropic/claude-opus-4.5": "anthropic/claude-opus-5.5",
  "google/gemini-2.5-flash-lite": "anthropic/claude-sonnet-5",
  "google/gemini-3-pro-preview": "anthropic/claude-sonnet-5",
  "xai/grok-4.1-fast-non-reasoning": "anthropic/claude-sonnet-5",
  "xai/grok-code-fast-1-thinking": "anthropic/claude-sonnet-5",
};

/** helper slot → catalog pin (title / artifact / fast) */
export const generatedAux: Record<string, string> = {
  "fast": "claude-haiku-4-5-20251001",
  "title": "claude-haiku-4-5-20251001",
  "artifact": "claude-haiku-4-5-20251001",
};

export const generatedCatalog = {
  version: 1,
  default_id: generatedDefaultId,
  default_pin: generatedDefaultPin,
  models: generatedModels,
  remaps: generatedRemaps,
  aux: generatedAux,
};
