[package]
edition = "2021"
license = "AGPL-3.0"
name = "simple_wal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bincode.workspace = true
file_store = {path = "../file-store"}
